[package]
name = "rust-ffi"
version = "0.1.0"
edition = "2021"
links = "foo"
build = "build.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
pkg-config = "0.3"
bindgen = "*"
